services:
    - name: rfd
      plan: free
      type: web
      env: python
      repo: https://github.com/joeydi/richmond-fire-district-1
      buildCommand: "./build.sh"
      startCommand: "gunicorn waterdistrict.wsgi:application"
      envVars:
          - key: DJANGO_SETTINGS_MODULE
            value: waterdistrict.settings
          - key: SECRET_KEY
            generateValue: true
          - key: PYTHON_VERSION
            value: 3.9.0
          - key: DATABASE_URL
            fromDatabase:
                name: rfd-db
                property: connectionString

databases:
    - name: rfd-db
      plan: free
      ipAllowList: []
