# Generated by Django 2.2.2 on 2019-06-23 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('water_gallons_used', models.IntegerField(default=0)),
                ('water_tank_level', models.IntegerField(default=0)),
                ('chlorinator_tank_level', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
